name: Hexo Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ericzyh/github-actions-hexo@master
        with: 
          username: zhaoyuhao   
          email: 8040334@qq.com
